connection: &connection
  adapter: postgresql
  encoding: unicode
  host:     localhost
  pool: 5
  username: workshops
  password: password1

development:
  <<: *connection
  database: workshops_development

test:
  adapter: postgresql
  database: travis_ci_test
  username: postgres